[package]
name = "rust-perf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.82"
wasm-bindgen-test = "0.3.32"
console_error_panic_hook = "0.1.7"
sha3 = "0.10.4"
js-sys = "0.3.9"